#!/bin/bash

# NestedBird  Copyright (C) 2016-2017  Michael Haddon
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DATE=`date +%Y-%m-%d:%H:%M:%S`
# nohup java -jar -DenvTarget=live /var/www/sound.dev/NestedBird.war > "/var/www/sound.dev/logs/$DATE.log"  2>&1 &
nohup java -jar /var/www/sound.dev/NestedBird.war > "/var/www/sound.dev/logs/$DATE.log"  2>&1 &
echo Started server with ID: $(/var/www/sound.dev/nb_get_pid)

rm -f /var/www/sound.dev/logs/__current.log
ln -s "/var/www/sound.dev/logs/$DATE.log" /var/www/sound.dev/logs/__current.log
#tail -0f /var/www/sound.dev/logs/__current.log